-- Dropping tables (without CASCADE CONSTRAINTS)
DROP TABLE IF EXISTS CP1_EMPRESA;

DROP TABLE IF EXISTS CP1_CONVENIO;

DROP TABLE IF EXISTS CP1_AREA_ATUACAO;

DROP TABLE IF EXISTS CP1_UNIDADE;

DROP TABLE IF EXISTS CP1_ENDERECO_UNIDADE;

DROP TABLE IF EXISTS CP1_MEDICO_UNIDADE;

DROP TABLE IF EXISTS CP1_MEDICO;

DROP TABLE IF EXISTS CP1_CLIENTE;

DROP TABLE IF EXISTS CP1_ENDERECO_CLIENTE;

DROP TABLE IF EXISTS CP1_COMORBIDADE;

DROP TABLE IF EXISTS CP1_HISTORICO_SAUDE_CLIENTE;

DROP TABLE IF EXISTS CP1_HISTORICO_HOSPITAL_CLIENTE;

DROP TABLE IF EXISTS CP1_CIDADE;

DROP TABLE IF EXISTS CP1_ESTADO;

DROP TABLE IF EXISTS CP1_ESTADO_CIVIL;

DROP TABLE IF EXISTS AUDITORIA_CP1_EMPRESA;

-- Sequences are replaced by IDENTITY in MSSQL
CREATE TABLE
    CP1_ESTADO (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOME VARCHAR(20)
    );

CREATE TABLE
    CP1_CIDADE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOME VARCHAR(20),
        ESTADO_ID INT,
        FOREIGN KEY (ESTADO_ID) REFERENCES CP1_ESTADO (ID) ON DELETE CASCADE
    );

CREATE TABLE
    CP1_EMPRESA (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        CNPJ VARCHAR(20),
        NOME VARCHAR(100),
        TIPO VARCHAR(100),
        TELEFONE VARCHAR(20),
        EMAIL VARCHAR(100)
    );

CREATE TABLE
    CP1_CONVENIO (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        EMPRESA_ID INT,
        NOME VARCHAR(100),
        VALOR FLOAT,
        TIPO_SERVICO VARCHAR(100),
        COBERTURA VARCHAR(100),
        CONTATO VARCHAR(100),
        VALIDADE DATE,
        FOREIGN KEY (EMPRESA_ID) REFERENCES CP1_EMPRESA (ID) ON DELETE CASCADE
    );

CREATE TABLE
    CP1_AREA_ATUACAO (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOME VARCHAR(100)
    );

CREATE TABLE
    CP1_UNIDADE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        EMPRESA_ID INT,
        AREA_ATUACAO_ID INT,
        NOME VARCHAR(100),
        TELEFONE VARCHAR(20),
        EMAIL VARCHAR(100),
        TIPO VARCHAR(100),
        CAPACIDADE INT,
        FOREIGN KEY (EMPRESA_ID) REFERENCES CP1_EMPRESA (ID) ON DELETE CASCADE,
        FOREIGN KEY (AREA_ATUACAO_ID) REFERENCES CP1_AREA_ATUACAO (ID) ON DELETE CASCADE
    );

CREATE TABLE
    CP1_ENDERECO_UNIDADE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        UNIDADE_ID INT UNIQUE NOT NULL,
        RUA VARCHAR(100),
        NUMERO VARCHAR(10),
        CEP VARCHAR(20),
        CIDADE_ID INT,
        FOREIGN KEY (UNIDADE_ID) REFERENCES CP1_UNIDADE (ID) ON DELETE CASCADE,
        FOREIGN KEY (CIDADE_ID) REFERENCES CP1_CIDADE (ID) ON DELETE CASCADE
    );

CREATE TABLE
    CP1_MEDICO (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOME VARCHAR(100),
        TELEFONE VARCHAR(20),
        EMAIL VARCHAR(100),
        ESPECIALIDADE VARCHAR(100),
        CRM VARCHAR(20)
    );

CREATE TABLE
    CP1_MEDICO_UNIDADE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        MEDICO_ID INT NOT NULL,
        UNIDADE_ID INT NOT NULL,
        HORARIO_ATENDIMENTO VARCHAR(100),
        FOREIGN KEY (MEDICO_ID) REFERENCES CP1_MEDICO (ID) ON DELETE CASCADE,
        FOREIGN KEY (UNIDADE_ID) REFERENCES CP1_UNIDADE (ID) ON DELETE CASCADE
    );

CREATE TABLE
    CP1_ESTADO_CIVIL (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOME VARCHAR(20)
    );

CREATE TABLE
    CP1_CLIENTE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        RG VARCHAR(20),
        NOME VARCHAR(100),
        SEXO CHAR(1) CHECK (SEXO IN ('M', 'F', 'O')),
        TELEFONE VARCHAR(20),
        EMAIL VARCHAR(100),
        DATA_NASCIMENTO DATE,
        CPF VARCHAR(20),
        CONVENIO_ID INT,
        ESTADO_CIVIL_ID INT,
        FOREIGN KEY (CONVENIO_ID) REFERENCES CP1_CONVENIO (ID) ON DELETE CASCADE,
        FOREIGN KEY (ESTADO_CIVIL_ID) REFERENCES CP1_ESTADO_CIVIL (ID) ON DELETE CASCADE
    );

CREATE TABLE
    CP1_ENDERECO_CLIENTE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        CLIENTE_ID INT UNIQUE NOT NULL,
        RUA VARCHAR(100),
        NUMERO VARCHAR(10),
        CEP VARCHAR(20),
        CIDADE_ID INT,
        FOREIGN KEY (CLIENTE_ID) REFERENCES CP1_CLIENTE (ID) ON DELETE CASCADE,
        FOREIGN KEY (CIDADE_ID) REFERENCES CP1_CIDADE (ID) ON DELETE CASCADE
    );

CREATE TABLE
    CP1_COMORBIDADE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOME VARCHAR(100)
    );

CREATE TABLE
    CP1_HISTORICO_SAUDE_CLIENTE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        CLIENTE_ID INT UNIQUE NOT NULL,
        COMORBIDADE_ID INT,
        DATA_REGISTRO DATE,
        FUMA BIT CHECK (FUMA IN (0, 1)),
        OBSERVACOES VARCHAR(100),
        FOREIGN KEY (CLIENTE_ID) REFERENCES CP1_CLIENTE (ID) ON DELETE CASCADE,
        FOREIGN KEY (COMORBIDADE_ID) REFERENCES CP1_COMORBIDADE (ID) ON DELETE CASCADE
    );

CREATE TABLE
    CP1_HISTORICO_HOSPITAL_CLIENTE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        CLIENTE_ID INT UNIQUE NOT NULL,
        DATA_REGISTRO DATE,
        HISTORICO_MEDICO VARCHAR(100),
        EXAMES_REALIZADOS VARCHAR(100),
        MEDICAMENTOS_PRESCRITOS VARCHAR(100),
        OBSERVACOES VARCHAR(100),
        FOREIGN KEY (CLIENTE_ID) REFERENCES CP1_CLIENTE (ID) ON DELETE CASCADE
    );

CREATE TABLE
    AUDITORIA_CP1_EMPRESA (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        OPERACAO VARCHAR(10),
        DATA_OPERACAO DATE,
        USUARIO VARCHAR(50),
        CNPJ_OLD VARCHAR(20),
        NOME_OLD VARCHAR(100),
        TIPO_OLD VARCHAR(100),
        TELEFONE_OLD VARCHAR(20),
        EMAIL_OLD VARCHAR(100),
        CNPJ_NEW VARCHAR(20),
        NOME_NEW VARCHAR(100),
        TIPO_NEW VARCHAR(100),
        TELEFONE_NEW VARCHAR(20),
        EMAIL_NEW VARCHAR(100)
    );